<?php

namespace App\Models;

use Doctrine\ORM\EntityRepository;

/**
 * LikeRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class LikeRepository extends EntityRepository
{
}
